In [3]:
!pip install numpy

In [1]:
import numpy as np

In [8]:
def abs(x) :
    return 10

In [10]:
arr = [1, 2, 3, 4]
a = np.array(arr)
print( type(a) )

<class 'numpy.ndarray'>


In [11]:
a[0:2]

array([1, 2])

In [12]:
np.zeros( 10 , dtype=int )

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones( 10, dtype=int )

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
# 이건?
np.ones( 10, dtype=str )

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [17]:
a = np.ones( [3, 3] , dtype=int )
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
# 위 아래 같다.
a = np.ones( (3, 3) , dtype=int )
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [21]:
arr = [[1,2],
       [3,4]]

a = np.array(arr)
print(a)

[[1 2]
 [3 4]]


In [22]:
# 요소 갯수
len( a )

2

In [26]:
# 인덱스
print(a [ 0 ])

[1 2]


In [25]:
# 슬라이싱
print(a[ : 1])

[[1 2]]


In [28]:
공부합시다 = [1, 2, 3, 4, 5]
공부합시다[ :2 ]
print(공부합시다[ :2 ])

[1, 2]


In [31]:
# vstack : 두 개의 ndarray를 vertical 방향으로 합칩니다.
# 1 x 4 -> 2 x 4
a = [1, 2, 3, 4]
print(np.vstack([a, a]))


[[1 2 3 4]
 [1 2 3 4]]


In [37]:
#  2 x 1 -> 4 x 1
b = [[1,2],
     [3, 4]]
print(np.vstack([b]))


[[1 2]
 [3 4]]


In [32]:
# hstack : 두 개의 ndarray를 horizontal 방향으로 합칩니다.
# 1 x 4 -> 1 x 8
a = [1, 2, 3, 4]
print(np.hstack([a, a]))

[1 2 3 4 1 2 3 4]


In [36]:
# 2 x 1 -> 4 x 1
b = [[1,2],
     [3, 4]]

print(np.hstack(b))

[1 2 3 4]


In [ ]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]